### ISSUE TITLE
Hybrid Layout: Show Both Screens option broken.

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/desmume#36]
In particular it still shows both screens to the side with hybrid layout scale set to 3 in recent versions of the core.  Scale 1 disables one of the screens as it should, but scale 1 is broken and runs at a lower, unreadable resolution than native.  Desmume 2015 doesn't have this issue, but I presume it's out of date.

**Comment by bearoso** [comment]
Thanks for the heads-up. Knowing me, I overlooked this when rewriting it. I'll check it out.

**Comment by n1ghttrap** [comment]
No problem.  Just let me know when the update is available from the
retroarch core update and I'll let you know how it works.  Thanks!

**Comment by bearoso** [comment]
Should be fixed in 7b8403b.

**Comment by n1ghttrap** [comment]
Thanks a lot, I'll try it when I get home.

**Comment by n1ghttrap** [comment]
Sadly, it still seems to do exhibit the issue with the same combination of settings with the latest Retroarch nightly and core as of 4/10 9pm.  Scale 3 + Show Both Screens off still shows both screens in hybrid mode.  Scale 1 hides the 2nd screen as it should, but is too blurry to use.

**Comment by bearoso** [comment]
Buildbot hasn't come through yet on Windows. Last update was April 3. I'll check for a compilation problem.

**Comment by bearoso** [comment]
Still compiles. Just give it time, I suppose. Here's the x86_64 dll if you want to try it.
[desmume_libretro.zip](https://github.com/libretro/desmume/files/1899488/desmume_libretro.zip)
